services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    command: python -m flask run --host=0.0.0.0 --port=5000 --debug
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - nginx

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/var/www/static  # 📂 Монтируем статику
    depends_on:
      - backend

volumes:
  postgres_data: